import * as OTPAuth from 'otpauth';

const TOTP_config = {
    issuer: "EvoTicket",
    label: "ticket",
    algorithm: "SHA1",
    digits: 6,
    period: 30
};

/* 
QR code contains: tid + otp
- otp is generated by the combination of: secretSeed + currentTime;
-----------------
    Input: tid + secretSeed (data received from server backend API)
    Output: QR code data (string format)
*/
export const generateQrCodeData = (tid: string, secretSeed: string): string => {
    try {
        // generate OTP
        const totp = new OTPAuth.TOTP({
            ...TOTP_config,
            secret: OTPAuth.Secret.fromBase32(secretSeed)
        });
        const userOtp = totp.generate();

        // generate QRCode Data
        const qrCodeDataObject = {
            tid: tid,
            otp: userOtp
        };
        return JSON.stringify(qrCodeDataObject);

    } catch (error) {
        console.log("Generate QRCode Data failed!\n", error);
        return "";
    }
}

/* 
    Input: secretSeed (save from server backend API) + userOtp (received when scanning QR)
    Output: valid (true) || invalid (false)
*/
export const verifyQrCode = (secretSeed: string, userOtp: string): boolean => {
    try {
        // generate and verify OTP
        const totp = new OTPAuth.TOTP({
            ...TOTP_config,
            secret: OTPAuth.Secret.fromBase32(secretSeed)
        });

        const result = totp.validate({
            token: userOtp,
            window: 1
        });

        return result !== null;
    } catch (error) {
        console.log("Verify QRCode failed!\n", error);
        return false;
    }
};